# Generated by Django 5.1.4 on 2025-01-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_expirence'),
    ]

    operations = [
        migrations.AddField(
            model_name='expirence',
            name='organization',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
