# Generated by Django 5.1.4 on 2025-01-11 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_expirence_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
